[project]
name = "torch_prelude"
dynamic = ["version"]
description = "torch prelude"
#requires-python = ">=3.10"
authors = [
  { name = "Peter Jin" },
]
license = { text = "ISC OR MIT OR Apache-2.0" }
#keywords = []
#classifiers = []
dependencies = [
  "torch>=2",
]
