[project]
name = "torch_prelude"
requires-python = ">=3.10"
dynamic = ["version"]
description = "pytorch prelude"
authors = [
  { name = "Peter Jin" },
]
keywords = []
license = { text = "ISC OR MIT OR Apache-2.0" }
dependencies = [
  "torch>=2.0",
]
classifiers = []
